"""
src/markdown_reporter.py
------------------------
Output Stage — Markdown Report Generator
Converts PipelineResult into a structured, human-readable Markdown report.
This satisfies the assignment requirement: "Output: Markdown + GitHub API".
"""

from datetime import datetime
from src.reviewer import ReviewComment, SEVERITY_LEVELS

SEVERITY_EMOJI = {
    "critical": "🔴",
    "high": "🟠",
    "medium": "🟡",
    "low": "🔵",
    "info": "⚪",
}

CATEGORY_EMOJI = {
    "bug": "🐛",
    "security": "🔒",
    "performance": "⚡",
    "style": "✨",
    "maintainability": "🔧",
    "documentation": "📝",
    "error_handling": "🛡",
    "type_safety": "🏷",
}


def generate_markdown_report(
    repo_name: str,
    comments: list[ReviewComment],
    metadata: dict,
    errors: list[str] | None = None,
) -> str:
    """
    Generate a full Markdown review report from a list of ReviewComment objects.

    Parameters
    ----------
    repo_name : str
        Display name of the reviewed repository.
    comments : list[ReviewComment]
        All review comments produced by the agent.
    metadata : dict
        Repository metadata from RepositoryIngestor.get_repo_metadata().
    errors : list[str] | None
        Any pipeline errors to surface in the report.

    Returns
    -------
    str
        Complete Markdown string ready to write to a .md file or post as a PR body.
    """
    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    lines: list[str] = []

    # ── Header ────────────────────────────────────────────────────────
    lines += [
        f"# 🔬 AI Code Review Report — `{repo_name}`",
        "",
        f"> Generated by **CodeSight** on {now}  ",
        f"> Total files scanned: **{metadata.get('total_source_files', '?')}**  ",
        f"> Language breakdown: {_fmt_ext_breakdown(metadata.get('extension_breakdown', {}))}",
        "",
        "---",
        "",
    ]

    if not comments:
        lines += [
            "## ✅ No Issues Found",
            "",
            "The agent reviewed all parseable files and found nothing to flag.",
            "This could mean the code is clean, or that the files were too large / non-Python.",
            "",
        ]
        return "\n".join(lines)

    # ── Summary table ─────────────────────────────────────────────────
    by_sev: dict[str, int] = {}
    for c in comments:
        by_sev[c.severity] = by_sev.get(c.severity, 0) + 1

    high_conf = [c for c in comments if not c.low_confidence]
    low_conf  = [c for c in comments if c.low_confidence]
    avg_conf  = int(sum(c.confidence for c in comments) / len(comments))

    lines += [
        "## 📊 Summary",
        "",
        f"| Metric | Value |",
        f"|---|---|",
        f"| Total issues | **{len(comments)}** |",
        f"| Average confidence | **{avg_conf}%** |",
        f"| High confidence (≥60%) | {len(high_conf)} |",
        f"| Needs verification (<60%) | {len(low_conf)} |",
    ]
    for sev in SEVERITY_LEVELS:
        count = by_sev.get(sev, 0)
        if count:
            lines.append(f"| {SEVERITY_EMOJI[sev]} {sev.capitalize()} | {count} |")
    lines += ["", "---", ""]

    # ── High confidence issues ────────────────────────────────────────
    if high_conf:
        lines += [
            "## ✅ High Confidence Issues",
            "",
            "_These comments have confidence ≥ 60% — the agent is reasonably certain._",
            "",
        ]
        for c in _sort_comments(high_conf):
            lines += _render_comment_md(c)

    # ── Low confidence issues ─────────────────────────────────────────
    if low_conf:
        lines += [
            "---",
            "",
            "## ⚠️ Verify These — Low Confidence",
            "",
            "_Confidence < 60%. These may be false positives. A human should verify each one._",
            "",
        ]
        for c in _sort_comments(low_conf):
            lines += _render_comment_md(c, verify=True)

    # ── File breakdown ────────────────────────────────────────────────
    files_hit: dict[str, int] = {}
    for c in comments:
        files_hit[c.file_path] = files_hit.get(c.file_path, 0) + 1

    lines += [
        "---",
        "",
        "## 📁 Issues by File",
        "",
        "| File | Issues |",
        "|---|---|",
    ]
    for fp, count in sorted(files_hit.items(), key=lambda x: -x[1]):
        lines.append(f"| `{fp}` | {count} |")

    lines += [""]

    # ── Errors ────────────────────────────────────────────────────────
    if errors:
        lines += [
            "---",
            "",
            "## ⚠️ Pipeline Errors",
            "",
            "_These nodes could not be reviewed due to LLM or parsing errors:_",
            "",
        ]
        for err in errors:
            lines.append(f"- {err}")
        lines.append("")

    # ── Footer ────────────────────────────────────────────────────────
    lines += [
        "---",
        "",
        "_Report generated by [CodeSight](https://github.com) — Autonomous AI Code Review Agent_  ",
        "_Low-confidence items are flagged automatically. Always apply human judgment._",
    ]

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _render_comment_md(c: ReviewComment, verify: bool = False) -> list[str]:
    """Render a single ReviewComment as a Markdown block."""
    verify_tag = " **`⚠ VERIFY THIS`**" if verify else ""
    cat_emoji = CATEGORY_EMOJI.get(c.category, "❓")
    sev_emoji = SEVERITY_EMOJI.get(c.severity, "⚪")

    lines = [
        f"### {sev_emoji} {c.title}{verify_tag}",
        "",
        f"| Field | Value |",
        f"|---|---|",
        f"| Severity | `{c.severity}` |",
        f"| Category | {cat_emoji} `{c.category}` |",
        f"| File | `{c.file_path}` |",
        f"| Scope | `{c.node_name}` |",
    ]
    if c.line_hint and c.line_hint != "N/A":
        lines.append(f"| Line(s) | `{c.line_hint}` |")
    lines.append(f"| Confidence | `{c.confidence}%` |")
    lines += [
        "",
        c.body,
        "",
    ]
    if c.suggestion:
        lines += [
            "**💡 Suggestion:**",
            "",
            f"> {c.suggestion}",
            "",
        ]
    lines.append("---" if not verify else "")
    lines.append("")
    return lines


def _sort_comments(comments: list[ReviewComment]) -> list[ReviewComment]:
    return sorted(comments, key=lambda c: SEVERITY_LEVELS.index(c.severity))


def _fmt_ext_breakdown(breakdown: dict) -> str:
    if not breakdown:
        return "N/A"
    return ", ".join(f"`{ext}` ({n})" for ext, n in sorted(breakdown.items(), key=lambda x: -x[1]))